### ISSUE TITLE
Maximum call stack size exceeded when creating objects

### ISSUE THREAD

**Issue by sbruchmann** [whastings/protomatter.js#18]
Hello @whastings,

please take a look at the following simplified example code:
```javascript
"use strict";

var Protomatter = require("protomatter");

var Model = Protomatter.create({
    private: {
        _properties: null
    },

    init: function init(properties) {
        this._properties = properties;
    }
});

var File = Model.extend({
    init: function init(path) {
        this.callSuper("init", {
            path: path
        });
    }
});

var JSONFile = File.extend({});
```

As soon as I try to `create` a new `JSONFile` object, it will throw the following error:
```shell
$ node example.js
$
$ (null):0
$ (null)
$
$ RangeError: Maximum call stack size exceeded
```

Is this a bug with _protomatter_ or am I misusing it?

**Comment by whastings** [comment]
Hi Steffen,

Thank you for bringing this issue to my attention. It's an interesting case that I didn't account for. Basically, when you create a `JSONFile`, the `init()` method in `File` runs because `JSONFile` doesn't have its own `init()` method. But it does have its own `callSuper()` method. So when creating a `JSONFile`, the `callSuper()` call in `File`'s `init()` just calls `File`'s `init()` again, and that causes the infinite recursion. I should have a fix for this ready in a few days. Thanks again for filing the issue!

As for usage, keep in mind that the `private` section of the prototype definition is only for private methods. Any property assigned to `this` in your `init()` will be private automatically. You don't have to do anything special to make it private. You can still name it with an underscore prefix if you want, but it won't be accessible from outside the object's own methods.

**Comment by whastings** [comment]
Okay, I just pushed version 0.2.1 with a fix for this issue. Feel free to reopen this issue if you're still having trouble, or another issue if you find anything else.

**Comment by sbruchmann** [comment]
I am sorry for the late response. Everything’s working as expected now. And thank you for the note on the usage of the `private` property, very appreciated!
